baseURL = "https://5f06fa0bae2fc5c227d32a7b--romantic-almeida-3936d3.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Jane Doe"
theme = "theme-used"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm Jane Doe"
author = "Jane Doe"
description = "Call me Jane"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]


## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

