# baseURL = "http://osbornesaka.tech"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Osborne Saka"
theme = "theme-used"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Osborne Ofosu Saka"
author = "Osborne Ofosu Saka"
description = "I am a coder who lives in Accra, Ghana."
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["blog"]
images = ["images/site-feature-image.png"]


## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/oskygh/"

[[params.socialIcons]]
icon = " fa-twitter" 
title = "twitter"
url = "https://www.twitter.com/oskygh"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:osborne.saka@gmail.com"



## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "blogs"
  url = "/blog/"

  [[menu.main]]
  name = "Resume"
  weight = 300
  identifier = "resume"
  url = "/resume/"

[[menu.main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"
